name: Run colrev update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * *'

# Note : requires github/settings/actions/general/workflow permissions/read and write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - run: |
          pip install git+https://github.com/CoLRev-Ecosystem/colrev.git#egg=colrev
      - run: |
          git config user.name "CoLRev update"
          git config user.email "actions@users.noreply.github.com"
          git config --global url.https://github.com/.insteadOf git://github.com/
          git branch colrev-update
          git checkout colrev-update
          colrev search -s data/search/md_curated.bib
          colrev search -s data/search/md_crossref.bib
          git push --set-upstream origin colrev-update
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "colrev-update"
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into master"
