name: Run colrev update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * *'

# Note : requires github/settings/actions/general/workflow permissions/read and write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - run: |
          pip install git+https://github.com/CoLRev-Ecosystem/colrev.git#egg=colrev
      - run: |
          git config user.name "CoLRev update"
          git config user.email "actions@users.noreply.github.com"
          colrev search -s data/search/md_curated.bib
          colrev search -s data/search/md_crossref.bib
      - name: Push if it changed
        run: |-
          git push